#!/bin/sh

pgrep -x dunst && notify-send -i ~/.scripts/pix/lock.png "Locking computer..." &&

i3lock-fancy -t 'Show me what you got!'

# In five seconds, turn off display unless key press in last 4 seconds.
sleep 7 && [ 4000 -lt "$(xssstate -i)" ] &&  pgrep -x i3lock && xset dpms force off
